package com.example.mareasv7.ui
import androidx.compose.foundation.*;import androidx.compose.foundation.layout.*;import androidx.compose.foundation.shape.*;import androidx.compose.material3.*;import androidx.compose.runtime.Composable;import androidx.compose.ui.*;import androidx.compose.ui.graphics.Color;import androidx.compose.ui.text.font.FontWeight;import androidx.compose.ui.text.style.TextAlign;import androidx.compose.ui.unit.*;import com.example.mareasv7.data.*
@Composable fun Page(title:String,compact:Boolean,content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=if(compact)28.dp else 24.dp,vertical=if(compact)18.dp else 24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(title,color=Cyan,fontWeight=FontWeight.Bold,fontSize=if(compact)14.sp else 22.sp);Spacer(Modifier.height(8.dp));content();Spacer(Modifier.height(if(compact)26.dp else 10.dp))}}
@Composable fun Home(d:Data,c:Boolean)=Page("MAREAS V7 PRO",c){Text(d.place,color=Green,fontSize=10.sp,textAlign=TextAlign.Center);Text("${"%.2f".format(d.level)} m",color=Color.White,fontSize=36.sp,fontWeight=FontWeight.Black);Text(if(d.rising)"FLUJO ↑" else "REFLUJO ↓",color=Cyan);d.events.firstOrNull()?.let{Text("${if(it.type.startsWith("pl"))"Pleamar" else "Bajamar"} ${it.time}",color=Color.White)};Spacer(Modifier.height(8.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){Card("Viento","${d.wind.toInt()} km/h",Cyan,Modifier.weight(1f));Card("Oleaje","${"%.1f".format(d.wave)} m",Purple,Modifier.weight(1f))};Spacer(Modifier.height(7.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(7.dp)){Card("Temp","${d.temp.toInt()}°C",Amber,Modifier.weight(1f));Card("UV","${"%.1f".format(d.uv)}",Amber,Modifier.weight(1f))};Spacer(Modifier.height(7.dp));Card("Luna / coeficiente","${d.moon} · ${d.coefficient}",Purple,Modifier.fillMaxWidth())}
@Composable fun Tides(d:Data,c:Boolean)=Page("MAREAS +24H",c){Chart(d.tide,Cyan,Modifier.fillMaxWidth().height(if(c)125.dp else 230.dp));Axis();d.events.forEach{Stat(if(it.type.startsWith("pl"))"Pleamar" else "Bajamar","${it.time} · ${"%.2f".format(it.height)} m",if(it.type.startsWith("pl"))Cyan else Amber)}}
@Composable fun Weather(d:Data,c:Boolean)=Page("TIEMPO",c){Text("${d.temp.toInt()}°",color=Color.White,fontSize=42.sp,fontWeight=FontWeight.Black);Chart(d.temp24,Amber,Modifier.fillMaxWidth().height(115.dp));Axis();Stat("Sensación","${d.feels.toInt()}°",Amber);Stat("Humedad","${d.humidity}%",Cyan);Stat("Presión","${d.pressure.toInt()} hPa",Purple)}
@Composable fun Wind(d:Data,c:Boolean)=Page("VIENTO",c){Box(Modifier.size(130.dp).background(Panel,CircleShape),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Text(compass(d.windDir),color=Cyan,fontSize=28.sp,fontWeight=FontWeight.Black);Text("${d.wind.toInt()} km/h",color=Color.White)}};Chart(d.wind24,Cyan,Modifier.fillMaxWidth().height(95.dp));Axis();Chart(d.gust24,Amber,Modifier.fillMaxWidth().height(95.dp));Stat("Rachas","${d.gust.toInt()} km/h",Amber)}
@Composable fun Sea(d:Data,c:Boolean)=Page("OLEAJE Y MAR",c){Stat("Estado",sea(d.wave),Green);Stat("Altura","${"%.1f".format(d.wave)} m",Cyan);Stat("Periodo","${d.period.toInt()} s",Purple);Stat("Dirección","${d.waveDir.toInt()}°",Cyan);Stat("Mar de fondo","${"%.1f".format(d.swell)} m",Purple);Stat("Agua","${d.seaTemp.toInt()}°C",Cyan)}
@Composable fun UV(d:Data,c:Boolean)=Page("RADIACIÓN UV",c){Text("${"%.1f".format(d.uv)}",color=Amber,fontSize=42.sp,fontWeight=FontWeight.Black);Text(uv(d.uv),color=Green);Chart(d.uv24,Amber,Modifier.fillMaxWidth().height(115.dp));Axis();Stat("Protección",if(d.uv<3)"Básica" else "Crema + gafas",Green)}
@Composable fun Beach(d:Data,c:Boolean)=Page("MODO PLAYA",c){val score=(if(d.uv<8)1 else 0)+(if(d.wave<1.2)1 else 0)+(if(d.wind<25)1 else 0);Text(if(score==3)"EXCELENTE" else if(score==2)"BUENA" else "REGULAR",color=if(score>=2)Green else Amber,fontSize=28.sp,fontWeight=FontWeight.Black);Stat("Oleaje","${"%.1f".format(d.wave)} m",Cyan);Stat("UV","${"%.1f".format(d.uv)}",Amber);Stat("Viento","${d.wind.toInt()} km/h",Cyan);Stat("Agua","${d.seaTemp.toInt()}°C",Purple)}
@Composable fun Fishing(d:Data,c:Boolean)=Page("MODO PESCA",c){val good=d.coefficient>75&&d.wind<25;Text(if(good)"FAVORABLE" else "NORMAL",color=if(good)Green else Amber,fontSize=28.sp,fontWeight=FontWeight.Black);Stat("Coeficiente","${d.coefficient}",Purple);Stat("Luna",d.moon,Purple);d.events.take(2).forEach{Stat(if(it.type.startsWith("pl"))"Pleamar" else "Bajamar",it.time,if(it.type.startsWith("pl"))Cyan else Amber)};Stat("Presión","${d.pressure.toInt()} hPa",Cyan)}
@Composable fun Card(a:String,b:String,c:Color,m:Modifier){androidx.compose.material3.Card(m,colors=CardDefaults.cardColors(containerColor=Panel)){Column(Modifier.padding(11.dp)){Text(a,color=c,fontSize=9.sp);Text(b,color=Color.White,fontWeight=FontWeight.Bold)}}}
@Composable fun Stat(a:String,b:String,c:Color){androidx.compose.material3.Card(Modifier.fillMaxWidth().padding(vertical=3.dp),colors=CardDefaults.cardColors(containerColor=Panel)){Row(Modifier.fillMaxWidth().padding(11.dp),horizontalArrangement=Arrangement.SpaceBetween){Text(a,color=c);Text(b,color=Color.White,fontWeight=FontWeight.Bold)}}}
@Composable fun Axis(){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){listOf("Ahora","+6h","+12h","+18h","+24h").forEach{Text(it,color=Muted,fontSize=8.sp)}}}
private fun compass(d:Double)=arrayOf("N","NE","E","SE","S","SW","W","NW")[((d/45).toInt()+8)%8];private fun sea(v:Double)=if(v<.5)"Mar rizada" else if(v<1.25)"Marejadilla" else "Marejada";private fun uv(v:Double)=if(v<3)"Bajo" else if(v<6)"Moderado" else if(v<8)"Alto" else "Muy alto"
